# Parte 1

## Verificando versão

In [ ]:
!python --version

Python 3.7.10

## Importanto e primeiro contato com pandas

In [ ]:
import pandas as pd

[Documentação IO Pandas](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html)

In [ ]:
dados = pd.read_csv('db.csv', sep=';')

In [ ]:
dados.head()

               Nome  ...      Valor
0     Jetta Variant  ...   88078.64
1            Passat  ...  106161.94
2          Crossfox  ...   72832.16
3               DS5  ...  124549.07
4  Aston Martin DB4  ...   92612.10

[5 rows x 7 columns]

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 258 entries, 0 to 257
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Nome           258 non-null    object
 1   Motor          258 non-null    object
 2   Ano            258 non-null    int64
 3   Quilometragem  197 non-null    float64
 4   Zero_km        258 non-null    bool
 5   Acessórios     258 non-null    object
 6   Valor          258 non-null    float64
dtypes: bool(1), float64(2), int64(1), object(3)
memory usage: 12.5+ KB

In [ ]:
dados.describe()

               Ano  Quilometragem          Valor
count   258.000000     197.000000     258.000000
mean   2007.511628   58278.421320   98960.513101
std       9.725906   35836.733259   29811.932305
min    1990.000000     107.000000   50742.100000
25%    1999.000000   27505.000000   70743.512500
50%    2008.000000   55083.000000   97724.380000
75%    2018.000000   90495.000000  124633.302500
max    2019.000000  119945.000000  149489.920000

# Parte 2

## Tuplas

In [ ]:
1,2,3

(1, 2, 3)

In [ ]:
(1,2,3)

(1, 2, 3)

In [ ]:
nome = 'uno'
valor = 40300.0
(nome, valor)

('uno', 40300.0)

Transformação para tuplas -> Builin fuction: **tuple()**

In [ ]:
[1,2,3]

[1, 2, 3]

In [ ]:
verificando = tuple([1,2,3])

In [ ]:
type(verificando)

tuple

### Seleção com tuplas

In [ ]:
numeros = tuple(range(1,10))

In [ ]:
numeros

(1, 2, 3, 4, 5, 6, 7, 8, 9)

In [ ]:
numeros[0]

1

In [ ]:
numeros[-1]

9

In [ ]:
numeros[3:8]

(4, 5, 6, 7, 8)

In [ ]:
numeros[1::2]

(2, 4, 6, 8)

In [ ]:
numeros_grandes = tuple(range(50, 55))

In [ ]:
nova_tupla = (1, 2, 3, numeros_grandes)

In [ ]:
nova_tupla

(1, 2, 3, (50, 51, 52, 53, 54))

In [ ]:
nova_tupla[-1][2]

52

### Iterando com tuplas

In [ ]:
numeros = tuple(range(0,3))

In [ ]:
numeros

(0, 1, 2)

In [ ]:
for item in numeros:
    print(item)

0
1
2

In [ ]:
num1, num2, num3 = numeros
print(num1, num2, num3, sep='-')

0-1-2

In [ ]:
_, A, _ = numeros

In [ ]:
A

1

In [ ]:
B, *_ = numeros

In [ ]:
B

0

Função zip()
[documentação aqui](https://docs.python.org/3/library/functions.html#zip)

In [ ]:
lista1 = ['ana', 'marcos', 'joao']
lista2 = [22, 23, 30]
print(lista1, lista2)

['ana', 'marcos', 'joao'] [22, 23, 30]

In [ ]:
pessoa = list(zip(lista1, lista2))

In [ ]:
for item in pessoa:
    print(item)

('ana', 22)
('marcos', 23)
('joao', 30)

In [ ]:
for nome, idade in pessoa:
    print(nome,', idade: ', idade)

ana , idade:  22
marcos , idade:  23
joao , idade:  30

In [ ]:
for nome, idade in pessoa:
    if(idade >= 30):
        print(nome, idade,'tem trinta ou mais anos')

joao 30 tem trinta ou mais anos

# Parte 3

## Dicionarios

In [ ]:
nomes = ['ana', 'marcos', 'joao']
idades = [22, 23, 30]

In [ ]:
idades[nomes.index('ana')]

22

In [ ]:
pessoa = dict(zip(nomes, idades))
print(pessoa)

{'ana': 22, 'marcos': 23, 'joao': 30}

In [ ]:
dicionario_pessoa = {'ana': 22, 'joao': 30, 'marcos': 23}
print(dicionario_pessoa)

{'ana': 22, 'joao': 30, 'marcos': 23}

### Operações com dicionarios

In [ ]:
nomes = ['ana', 'marcos', 'joao']
idades = [22, 23, 30]
pessoa = dict(zip(nomes, idades))

In [ ]:
pessoa

{'ana': 22, 'joao': 30, 'marcos': 23}

> **Pega valor**

In [ ]:
pessoa['ana']

22

> **Verifica se existe**

In [ ]:
'ana' in pessoa

True

In [ ]:
'jocy' in pessoa

False

In [ ]:
'jocy' not in pessoa

True

> **Tamanho**

In [ ]:
len(pessoa)

3

> **Adiciona valor**

In [ ]:
pessoa['jocy'] = 27
print(pessoa)

{'marcos': 23, 'joao': 30, 'jocy': 27}

> **Remove valor**

In [ ]:
del pessoa['ana'] 
print(pessoa)

{'marcos': 23, 'joao': 30, 'jocy': 27}

### Funções dicionario:
[link](https://docs.python.org/3/tutorial/datastructures.html#dictionaries)

In [ ]:
# update(), copy(), pop() e clear()

In [ ]:
pessoa

{'joao': 30, 'jocy': 27, 'marcos': 23}

> atualiza e/ou adiciona

In [ ]:
pessoa.update({'joao': 33, 'carol':27})
print(pessoa)

{'marcos': 23, 'joao': 33, 'jocy': 27, 'carol': 27}

> copia estrutura de dados

In [ ]:
pessoa_copia = pessoa.copy()
print(pessoa_copia)

{'marcos': 23, 'joao': 33, 'jocy': 27, 'carol': 27}

> Removendo e tratando valores ao remover

In [ ]:
pessoa.pop('carol')

27

In [ ]:
pessoa.pop('carol', 'Não há dados para serem removidos')

'Não há dados para serem removidos'

> exclui tudo

In [ ]:
print(pessoa_copia)
pessoa_copia.clear()
print(pessoa_copia)

{'marcos': 23, 'joao': 33, 'jocy': 27, 'carol': 27}
{}

### Interando nos dicionarios

In [ ]:
pessoa = {'marcos': 23, 'joao': 30, 'ramirez': 27, 'maria': 22, 'samira': 27}
pessoa

{'joao': 30, 'marcos': 23, 'maria': 22, 'ramirez': 27, 'samira': 27}

In [ ]:
pessoa.keys()

dict_keys(['marcos', 'joao', 'ramirez', 'maria', 'samira'])

In [ ]:
pessoa.values()

dict_values([23, 30, 27, 22, 27])

In [ ]:
for key in pessoa.keys():
    print(pessoa[key])

23
30
27
22
27

In [ ]:
t_pessoa = pessoa.items()
print(t_pessoa)

dict_items([('marcos', 23), ('joao', 30), ('ramirez', 27), ('maria', 22), ('samira', 27)])

In [ ]:
for nome, idade in pessoa.items():
    print(nome, idade)

marcos 23
joao 30
ramirez 27
maria 22
samira 27

In [ ]:
for nome, idade in pessoa.items():
    if (idade > 25):
        print(nome)

joao
ramirez
samira

In [ ]:
dados = {
    'Crossfox': {'valor': 72000, 'ano': 2005}, 
    'DS5': {'valor': 125000, 'ano': 2015}, 
    'Fusca': {'valor': 150000, 'ano': 1976}, 
    'Jetta': {'valor': 88000, 'ano': 2010}, 
    'Passat': {'valor': 106000, 'ano': 1998}
}

In [ ]:
for item in dados.items():
    print(item[1]['ano'])

2005
2015
1976
2010
1998

# Parte 4

## Funçoes e metodos

In [1]:
dados = {
    'Crossfox': {'km': 35000, 'ano': 2005}, 
    'DS5': {'km': 17000, 'ano': 2015}, 
    'Fusca': {'km': 130000, 'ano': 1979}, 
    'Jetta': {'km': 56000, 'ano': 2011}, 
    'Passat': {'km': 62000, 'ano': 1999}
}

In [9]:
def km_media(dataset, ano_atual):
    for item in dataset.items():
        result = item[1]['km'] / (ano_atual - item[-1]['ano'])
        print(result)

In [10]:
km_media(dados, 2021)

2187.5
2833.3333333333335
3095.2380952380954
5600.0
2818.181818181818

In [11]:
def km_media(dataset, ano_atual):
    lista = []
    for item in dataset.items():
        result = item[1]['km'] / (ano_atual - item[-1]['ano'])
        lista.append(result)
    return lista

In [12]:
valores = km_media(dados, 2021)
valores

[2187.5, 2833.3333333333335, 3095.2380952380954, 5600.0, 2818.181818181818]

In [25]:
dados = {
    'Crossfox': {'km': 35000, 'ano': 2005}, 
    'DS5': {'km': 17000, 'ano': 2015}, 
    'Fusca': {'km': 130000, 'ano': 1979}, 
    'Jetta': {'km': 56000, 'ano': 2011}, 
    'Passat': {'km': 62000, 'ano': 1999}
}

In [53]:
def km_media(dataset, ano_atual):
    dicionario = {}
    for item in dataset.items():
        result = item[1]['km'] / (ano_atual - item[-1]['ano'])
        item[1].update({'km_media': result})
        dicionario.update({ item[0]: item[1] })
    return dicionario

In [ ]:
km_media(dados, 2021)

In [ ]:
dados

# Parte 5

## Pandas

In [1]:
import pandas as pd

### Criando dataframes e series

In [56]:
carros = ['Jetta Variant', 'Passat', 'Crossfox']
carros

['Jetta Variant', 'Passat', 'Crossfox']

In [58]:
carros_series = pd.Series(carros)
carros_series

0    Jetta Variant
1           Passat
2         Crossfox
dtype: object

In [59]:
dados = [
    {'Nome': 'Jetta Variant', 'Motor': 'Motor 4.0 Turbo', 'Ano': 2003, 'Quilometragem': 44410.0, 'Zero_km': False, 'Valor': 88078.64},
    {'Nome': 'Passat', 'Motor': 'Motor Diesel', 'Ano': 1991, 'Quilometragem': 5712.0, 'Zero_km': False, 'Valor': 106161.94},
    {'Nome': 'Crossfox', 'Motor': 'Motor Diesel V8', 'Ano': 1990, 'Quilometragem': 37123.0, 'Zero_km': False, 'Valor': 72832.16}
]

In [60]:
dados_dataframe = pd.DataFrame(dados)
dados_dataframe

            Nome            Motor   Ano  Quilometragem  Zero_km      Valor
0  Jetta Variant  Motor 4.0 Turbo  2003        44410.0    False   88078.64
1         Passat     Motor Diesel  1991         5712.0    False  106161.94
2       Crossfox  Motor Diesel V8  1990        37123.0    False   72832.16

In [61]:
dados = {
    'Nome': ['Jetta Variant', 'Passat', 'Crossfox'], 
    'Motor': ['Motor 4.0 Turbo', 'Motor Diesel', 'Motor Diesel V8'],
    'Ano': [2003, 1991, 1990],
    'Quilometragem': [44410.0, 5712.0, 37123.0],
    'Zero_km': [False, False, False],
    'Valor': [88078.64, 106161.94, 72832.16]
}

In [65]:
dados_dataframe = pd.DataFrame(dados)
dados_dataframe

            Nome            Motor   Ano  Quilometragem  Zero_km      Valor
0  Jetta Variant  Motor 4.0 Turbo  2003        44410.0    False   88078.64
1         Passat     Motor Diesel  1991         5712.0    False  106161.94
2       Crossfox  Motor Diesel V8  1990        37123.0    False   72832.16

### Importando dataset CSV

In [2]:
dataset = pd.read_csv('db.csv', sep=';')

In [3]:
dataset.head(5)

               Nome  ...      Valor
0     Jetta Variant  ...   88078.64
1            Passat  ...  106161.94
2          Crossfox  ...   72832.16
3               DS5  ...  124549.07
4  Aston Martin DB4  ...   92612.10

[5 rows x 7 columns]

In [73]:
dataset2 = pd.read_csv('db.csv', sep=';', index_col= 0)
dataset2.head()

                            Motor  ...      Valor
Nome                               ...
Jetta Variant     Motor 4.0 Turbo  ...   88078.64
Passat               Motor Diesel  ...  106161.94
Crossfox          Motor Diesel V8  ...   72832.16
DS5               Motor 2.4 Turbo  ...  124549.07
Aston Martin DB4  Motor 2.4 Turbo  ...   92612.10

[5 rows x 6 columns]

### Acessando colunas

In [75]:
dataset.head()

               Nome  ...      Valor
0     Jetta Variant  ...   88078.64
1            Passat  ...  106161.94
2          Crossfox  ...   72832.16
3               DS5  ...  124549.07
4  Aston Martin DB4  ...   92612.10

[5 rows x 7 columns]

In [79]:
dataset['Nome'].head()
#ele retorna uma series com um colchete

0       Jetta Variant
1              Passat
2            Crossfox
3                 DS5
4    Aston Martin DB4
Name: Nome, dtype: object

In [80]:
dataset[['Nome']].head()
#ele retorna um dataframe com dois colchete

               Nome
0     Jetta Variant
1            Passat
2          Crossfox
3               DS5
4  Aston Martin DB4

In [5]:
dataset[['Nome', 'Ano']][1:4]

       Nome   Ano
1    Passat  1991
2  Crossfox  1990
3       DS5  2019

In [7]:
dataset[:][1:4]

       Nome  ...      Valor
1    Passat  ...  106161.94
2  Crossfox  ...   72832.16
3       DS5  ...  124549.07

[3 rows x 7 columns]

### loc() 
[Documentação](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html)

In [84]:
dataset.head()

               Nome  ...      Valor
0     Jetta Variant  ...   88078.64
1            Passat  ...  106161.94
2          Crossfox  ...   72832.16
3               DS5  ...  124549.07
4  Aston Martin DB4  ...   92612.10

[5 rows x 7 columns]

In [92]:
dataset.loc[[0]]
#dataframe

            Nome  ...     Valor
0  Jetta Variant  ...  88078.64

[1 rows x 7 columns]

In [95]:
dataset.loc[0]
#series

Nome                                                 Jetta Variant
Motor                                              Motor 4.0 Turbo
Ano                                                           2003
Quilometragem                                                44410
Zero_km                                                      False
Acessórios       ['Rodas de liga', 'Travas elétricas', 'Piloto ...
Valor                                                      88078.6
Name: 0, dtype: object

In [113]:
dataset.loc[0:5, ['Motor','Ano']]

             Motor   Ano
0  Motor 4.0 Turbo  2003
1     Motor Diesel  1991
2  Motor Diesel V8  1990
3  Motor 2.4 Turbo  2019
4  Motor 2.4 Turbo  2006
5    Motor 1.8 16v  2012

In [104]:
dataset2.head()

                            Motor  ...      Valor
Nome                               ...
Jetta Variant     Motor 4.0 Turbo  ...   88078.64
Passat               Motor Diesel  ...  106161.94
Crossfox          Motor Diesel V8  ...   72832.16
DS5               Motor 2.4 Turbo  ...  124549.07
Aston Martin DB4  Motor 2.4 Turbo  ...   92612.10

[5 rows x 6 columns]

In [111]:
dataset2.loc[['Crossfox'], ['Ano', 'Motor']]

           Ano            Motor
Nome
Crossfox  1990  Motor Diesel V8

### iloc()
[Documentação](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html)

In [114]:
dataset.head()

               Nome  ...      Valor
0     Jetta Variant  ...   88078.64
1            Passat  ...  106161.94
2          Crossfox  ...   72832.16
3               DS5  ...  124549.07
4  Aston Martin DB4  ...   92612.10

[5 rows x 7 columns]

In [116]:
dataset.iloc[1]

Nome                                                        Passat
Motor                                                 Motor Diesel
Ano                                                           1991
Quilometragem                                                 5712
Zero_km                                                      False
Acessórios       ['Central multimídia', 'Teto panorâmico', 'Fre...
Valor                                                       106162
Name: 1, dtype: object

In [117]:
dataset.iloc[[1]]

     Nome  ...      Valor
1  Passat  ...  106161.94

[1 rows x 7 columns]

In [119]:
dataset.iloc[[1], [2,3]]

    Ano  Quilometragem
1  1991         5712.0

In [128]:
dataset.iloc[:4, 1::2]

             Motor  ...                                         Acessórios
0  Motor 4.0 Turbo  ...  ['Rodas de liga', 'Travas elétricas', 'Piloto ...
1     Motor Diesel  ...  ['Central multimídia', 'Teto panorâmico', 'Fre...
2  Motor Diesel V8  ...  ['Piloto automático', 'Controle de estabilidad...
3  Motor 2.4 Turbo  ...  ['Travas elétricas', '4 X 4', 'Vidros elétrico...

[4 rows x 3 columns]

In [129]:
dataset2.iloc[:4, 1::2]

                Ano  Zero_km      Valor
Nome
Jetta Variant  2003    False   88078.64
Passat         1991    False  106161.94
Crossfox       1990    False   72832.16
DS5            2019     True  124549.07

### Querys e condicionais

In [9]:
dataset.head()

               Nome  ...      Valor
0     Jetta Variant  ...   88078.64
1            Passat  ...  106161.94
2          Crossfox  ...   72832.16
3               DS5  ...  124549.07
4  Aston Martin DB4  ...   92612.10

[5 rows x 7 columns]

In [ ]:
dataset['Ano'] == 2013
#retorna uma series

In [15]:
dataset[(dataset['Ano'] == 2013) & (dataset['Quilometragem'] < 9000.0)]
#se passado dentro de uma seleção vai retornar o data frame

       Nome  ...      Valor
155  RX 350  ...  138823.81
156  Cayman  ...  117961.95

[2 rows x 7 columns]

In [16]:
(dataset['Ano'] == 2013) & (dataset['Quilometragem'] < 9000.0)

0      False
1      False
2      False
3      False
4      False
       ...
253    False
254    False
255    False
256    False
257    False
Length: 258, dtype: bool

In [22]:
dataset.query('Ano != 2013 & Quilometragem <= 9000').head()

                    Nome  ...      Valor
1                 Passat  ...  106161.94
11               Courier  ...   73919.53
26    Fiesta Rocam Sedan  ...   95347.75
38            California  ...   69770.18
47  Série 5 Gran Turismo  ...   90781.65

[5 rows x 7 columns]